# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: 			 false
markdown: 			 redcarpet
#relative_permalinks: true

# Setup
title:               R-338 Takım RCP Proje Sayfası
tagline:             'Akademik Bilişim 2016'
description:         'NBA DRAFT'
url:                 http://rcp-ab2016.github.io/
baseurl:             '/proje'
paginate:            5

# About/contact
author:
  name:              'Takım elemanları'
  url:               http://rcp-ab2016.github.io/
  email:             

# Custom vars
version:             1.0.0
